### ISSUE TITLE
Unable to create the pipeline using gitpath plugin git material name

### ISSUE THREAD

**Issue by vkvarma** [TWChennai/gocd-git-path-material-plugin#12]
step to reproducue  :- 
1)  name any material for git e.g. test1 and corresponding url.
2) delete the pipeline.
3) create the same name pipeline and use same material previously used.

Result :- 
not able to save the add pipeline with this change giving below error :- 

Cannot save SCM, found multiple SCMs called 'test1'. SCM names are case-insensitive and must be unique.

@nitink85

**Comment by chadlwilson** [comment]
Tried to replicate this with GoCD `20.3` and the forthcoming `2.1` version of the plugin and could not replicate. Suspect this might have actually been an issue with the way GoCD Server handled pluggable SCMs rather than a core issue with the plugin.

The current GoCD server wizard allows you to select and manage the Pluggable SCMs properly so when you create the same name pipeline you can select the previous SCM; or create a new one.
